### PR TITLE
Cgroupv2

### PR DESCRIPTION
**Pull request by underhax**
Change logic for setup_cgroup_v2_slice()
Add check nproc to REQUIRED_CMDS. 
Add multi CPU cores. 
The logic for creating CPU limits based on the period has been fixed. 
Additional logging has been improved.

### CODE REVIEW

**Comment by codebyoul** [comment]
Hello web studio bond,
Thanks for the PR, for the logique of CPU is not good, the CPU cores can managed in cpu quota since the value can be more than 100% if you have 8 cores you can put 800% this is the definition of cpu quota in systems:

CPUQuota=[¶](https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html#CPUQuota=)
This setting controls the cpu controller in the unified hierarchy.

Assign the specified CPU time quota to the processes executed. Takes a percentage value, suffixed with "%". The percentage specifies how much CPU time the unit shall get at maximum, relative to the total CPU time available on one CPU. Use values > 100% for allotting CPU time on more than one CPU. This controls the "cpu.max" attribute on the unified control group hierarchy and "cpu.cfs_quota_us" on legacy. For details about these control group attributes, see [Control Groups v2](https://docs.kernel.org/admin-guide/cgroup-v2.html) and [CFS Bandwidth Control](https://docs.kernel.org/scheduler/sched-bwc.html). Setting CPUQuota= to an empty value unsets the quota.

Example: CPUQuota=20% ensures that the executed processes will never get more than 20% CPU time on one CPU.

Added in version 213.

**Comment by underhax** [comment]
I understand everything, but do we want to introduce this into hestia cp? 
Look at what is indicated there when filling out the parameters.

Quote:
"CPUQuota=20% ensures that the executed processes will never get more than 20% CPU time on one CPU."

Apparently we have different understanding "on one CPU". Do you think users will fill in more than 100% when the description says 1 CPU? I understand this as a 1 core limitation. I could be wrong. But if not, it is logical to determine the number of cores and multiply by them.

It is up to you to decide whether to accept this pull request. 

However, pay attention to the formula that calculates the CPU limit according to the period. For cgroup v2 in my opinion, it calculates incorrectly in your code, which is why there was such an effect with the limitation that I wrote about in the issue.

Your: cpu_quota * 1000
My: (period_us * cpu_quota / 100) * cpu_cores

I changed this behavior and now on my production server the constraints work as I need them to. But of course I could be wrong as I am not an expert in cgroup.

**Comment by codebyoul** [comment]
Add cores in the script does not align with cgroup's design philosophy. Let's consider a scenario where a user needs to limit a package to utilize 2 cores out of 8 available cores. The current approach is suboptimal - instead, we should maintain consistency with cgroup's architectural principles.

For managing CPU limitations, cgroup provides a dedicated controller called cpuset, which I plan to implement in a future update. This controller is specifically designed to handle CPU core allocation, while CPU quota will serve its intended purpose more effectively.

Regarding CPU quota calculations I will check that normally :When a user specifies 20% utilization with a 500ms period, the quota is calculated like you suggest but without cores:
0.2 × 500,000 = 100,000 microseconds​​​​​​​​​​​​​​​​

**Comment by underhax** [comment]
About cores. Here, either change the description in the hestia with good examples, or add a separate parameter specifying the number of cores.

**Pull request closed without merging**
